### ISSUE TITLE
Some questions about the project

### ISSUE THREAD

**Issue by vmarchaud** [Streampunk/ceforama#2]
Hey !

I'm looking into this project because i want to render html in "headless" mode but chrome feels too slow. I've tried to compile the project without success (i'm under linux though).

I was mainly wondering whats the status of this ? Do you plan to actually use it one day ?

I also saw some of your other projects (phaneron or beamcoder which are awesome !) so i also wanted to thank you for all the work !

Regards

**Comment by sparkpunkd** [comment]
This project is on a list of projects "to be finished" as it will be a key component of Phaneron - creating software-generated graphical overlays. I expect to complete it during the autumn. The aim is to build a CasparCG-like application from a set of reusable Node building blocks. That will be a cross-platform project so ceforama will be checked to work under Linux at that point ... but for now my main development platform is Windows.

You might be interested in [elecular](https://githb.com/Streampunk/elecular) which performs a similar function to ceforama but from within an Electron context. That project is experimental but I know of one company that uses that approach to render HTML at 50fps.

Thanks for your interest in our work and happy media coding!

Regards,

Richard

**Comment by vmarchaud** [comment]
@sparkpunkd thanks for your quick response. To be a little more precise, our use case is to render content (which can be a image, gif or video) dynamically depending on the user as fast as possible. Definitely looking forward this implementation and i will check elecular too, thanks again !
